name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Gerar Estat√≠sticas Gerais
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: stats.svg
          
          base: header, repositories, metadata
          config_display: regular
          
          plugin_languages: no

      - name: Gerar Linguagens Mais Usadas
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: langs.svg
          
          base: ""
          
          plugin_languages: yes
          
          plugin_languages_ignored: "html, css, tex, latex, jupyter notebook"
          
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_colors: github
