name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics.plugin.languages.svg
          
          # --- VISUAL ---
          base: header, activity, community, repositories, metadata
          config_display: large
          
          # --- LINGUAGENS ---
          plugin_languages: yes
          plugin_languages_ignored: "tex, latex, jupyter notebook, html, css"
          plugin_languages_details: percentage, lines
          plugin_languages_limit: 8
          plugin_languages_colors: github
          
          # --- TÃ“PICOS ---
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
          plugin_topics_sort: stars
